import {
  CharacterAbilityScores, CharacterAdvancedClass,
  CharacterRace,
  CharacterStarterClass,
  EquipmentClass
} from '../data-access';


export const ClassModifierTableStarter = new Map<
  CharacterStarterClass,
  CharacterAbilityScores & {
    startingHp: number;
    startingMp: number;
    hpGain: number;
    mpGain: number;
    equipmentRequirements?: EquipmentClass;
  }
>([
  [
    CharacterStarterClass.Warrior,
    Object.freeze({
      str: 2,
      dex: 2,
      agi: 2,
      int: 0,
      per: 0,
      mnd: 0,
      luk: 0,
      startingHp: 26,
      startingMp: 20,
      hpGain: 14,
      mpGain: 8,
      equipmentRequirements: CharacterStarterClass.Warrior,
    }),
  ],
  [
    CharacterStarterClass.Priest,
    Object.freeze({
      str: 0,
      dex: 2,
      agi: 0,
      int: 2,
      per: 0,
      mnd: 2,
      luk: 0,
      startingHp: 22,
      startingMp: 24,
      hpGain: 10,
      mpGain: 12,
      equipmentRequirements: CharacterStarterClass.Priest,
    }),
  ],
  [
    CharacterStarterClass.Wizard,
    Object.freeze({
      str: 0,
      dex: 0,
      agi: 0,
      int: 2,
      per: 2,
      mnd: 2,
      luk: 0,
      startingHp: 20,
      startingMp: 26,
      hpGain: 8,
      mpGain: 14,
      equipmentRequirements: CharacterStarterClass.Wizard,
    }),
  ],
  [
    CharacterStarterClass.Thief,
    Object.freeze({
      str: 0,
      dex: 2,
      agi: 2,
      int: 0,
      per: 2,
      mnd: 0,
      luk: 0,
      startingHp: 24,
      startingMp: 22,
      hpGain: 12,
      mpGain: 10,
      equipmentRequirements: CharacterStarterClass.Thief,
    }),
  ],
  [
    CharacterStarterClass.Adventurer,
    Object.freeze({
      str: 1,
      dex: 1,
      agi: 1,
      int: 1,
      per: 1,
      mnd: 1,
      luk: 1,
      startingHp: 23,
      startingMp: 23,
      hpGain: 10,
      mpGain: 10,
    }),
  ],
  [
    CharacterStarterClass.Archer,
    Object.freeze({
      str: 0,
      dex: 2,
      agi: 1,
      int: 0,
      per: 2,
      mnd: 0,
      luk: 1,
      startingHp: 24,
      startingMp: 22,
      hpGain: 12,
      mpGain: 10,
      equipmentRequirements: CharacterStarterClass.Thief,
    }),
  ],
  [
    CharacterStarterClass.ElementalMaster,
    Object.freeze({
      str: 0,
      dex: 0,
      agi: 1,
      int: 2,
      per: 2,
      mnd: 1,
      luk: 0,
      startingHp: 22,
      startingMp: 24,
      hpGain: 8,
      mpGain: 14,
      equipmentRequirements: CharacterStarterClass.Wizard,
    }),
  ],
  [
    CharacterStarterClass.Creator,
    Object.freeze({
      str: 0,
      dex: 1,
      agi: 2,
      int: 1,
      per: 2,
      mnd: 0,
      luk: 0,
      startingHp: 23,
      startingMp: 23,
      hpGain: 11,
      mpGain: 11,
      equipmentRequirements: CharacterStarterClass.Thief,
    }),
  ],
  [
    CharacterStarterClass.Swordfighter,
    Object.freeze({
      str: 1,
      dex: 2,
      agi: 2,
      int: 0,
      per: 1,
      mnd: 0,
      luk: 0,
      startingHp: 26,
      startingMp: 20,
      hpGain: 14,
      mpGain: 8,
      equipmentRequirements: CharacterStarterClass.Warrior,
    }),
  ],
  [
    CharacterStarterClass.Knight,
    Object.freeze({
      str: 2,
      dex: 1,
      agi: 1,
      int: 0,
      per: 0,
      mnd: 2,
      luk: 0,
      startingHp: 26,
      startingMp: 20,
      hpGain: 14,
      mpGain: 8,
      equipmentRequirements: CharacterStarterClass.Warrior,
    }),
  ],
  [
    CharacterStarterClass.Lancer,
    Object.freeze({
      str: 2,
      dex: 2,
      agi: 1,
      int: 0,
      per: 1,
      mnd: 0,
      luk: 0,
      startingHp: 26,
      startingMp: 20,
      hpGain: 14,
      mpGain: 8,
      equipmentRequirements: CharacterStarterClass.Warrior,
    }),
  ],
  [
    CharacterStarterClass.RuneKnight,
    Object.freeze({
      str: 1,
      dex: 2,
      agi: 1,
      int: 1,
      per: 0,
      mnd: 1,
      luk: 0,
      startingHp: 24,
      startingMp: 22,
      hpGain: 12,
      mpGain: 10,
      equipmentRequirements: CharacterStarterClass.Warrior,
    }),
  ],
]);
